/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "inverse-surface": "#213145",
        "on-surface-variant": "#464554",
        "secondary-fixed-dim": "#bec6e0",
        "secondary-container": "#dae2fd",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-dim": "#cbdbf5",
        "tertiary-fixed": "#ffdcc5",
        "on-primary-fixed-variant": "#2f2ebe",
        "inverse-on-surface": "#eaf1ff",
        "primary-fixed": "#e1e0ff",
        "on-tertiary-fixed-variant": "#703700",
        "on-background": "#0b1c30",
        "secondary-fixed": "#dae2fd",
        "outline-variant": "#c7c4d7",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "primary-container": "#6063ee",
        "surface-bright": "#f8f9ff",
        "surface-container": "#e5eeff",
        "on-primary-container": "#fffbff",
        "surface-variant": "#d3e4fe",
        "primary-fixed-dim": "#c0c1ff",
        "on-surface": "#0b1c30",
        "on-primary-fixed": "#07006c",
        "on-secondary-container": "#5c647a",
        secondary: "#565e74",
        surface: "#f8f9ff",
        "tertiary-container": "#b55d00",
        "on-secondary-fixed": "#131b2e",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary": "#ffffff",
        background: "#f8f9ff",
        "on-primary": "#ffffff",
        "surface-container-low": "#eff4ff",
        outline: "#767586",
        tertiary: "#904900",
        "tertiary-fixed-dim": "#ffb783",
        error: "#ba1a1a",
        "surface-container-high": "#dce9ff",
        "on-tertiary-container": "#fffbff",
        "on-secondary-fixed-variant": "#3f465c",
        "on-tertiary-fixed": "#301400",
        primary: "#4648d4",
        "surface-tint": "#494bd6",
        "inverse-primary": "#c0c1ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        xl: "4rem",
        base: "4px",
        sm: "1rem",
        lg: "2.5rem",
        md: "1.5rem",
        xs: "0.5rem",
        "container-max": "1200px",
      },
      fontFamily: {
        inter: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        h1: ["var(--font-inter)", "Inter"],
        h2: ["var(--font-inter)", "Inter"],
        h3: ["var(--font-inter)", "Inter"],
        "body-md": ["var(--font-inter)", "Inter"],
        "body-sm": ["var(--font-inter)", "Inter"],
        "label-caps": ["var(--font-inter)", "Inter"],
      },
      fontSize: {
        h2: [
          "24px",
          { lineHeight: "1.3", letterSpacing: "-0.015em", fontWeight: "600" },
        ],
        "body-sm": [
          "13px",
          { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-md": [
          "15px",
          { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" },
        ],
        h1: [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        h3: [
          "18px",
          { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};

